#!/bin/sh
# Run by github/github codespaces after starting

# Use ZSH as my default shell (e.g. for SSH)
if ! grep -q "root.*/bin/zsh" /etc/passwd
then
  sudo chsh -s /bin/zsh root
fi


apt-get install -y \
  exa grc ripgrep shellcheck zsh-autosuggestions
