#!/bin/bash
sudo apt-get update
sudo apt-get install vim -y

git config --global pager.branch false
git config --global core.editor "vim"

# Use ZSH as the default shell, error may be thrown
sudo chsh -s $(which zsh)

if ! command -v zsh; then
  # Get zsh
  rm /etc/zsh/zlogin # ¯\_(ツ)_/¯
  sudo apt install zsh -yq
  # since the terminal switches to zsh, everything hangs
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sed '/exec zsh -l/d')"
  
  sudo apt install less
  
  git config --global color.ui true
  git config --global core.pager 'less -r'
  
  # Let's add a nice theme
  sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="norm"/' ~/.zshrc
fi

if [ ! -d "~/zsh-syntax-highlighting" ] ; then
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/zsh-syntax-highlighting
  echo "source ~/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" >> ${ZDOTDIR:-$HOME}/.zshrc
fi

if [ -f /home/linuxbrew/.linuxbrew/bin/brew ]; then
  test -d /home/linuxbrew/.linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
  test -r ~/.zshrc && echo "eval \"\$($(brew --prefix)/bin/brew shellenv)\"" >>~/.zshrc
  echo "eval \"\$($(brew --prefix)/bin/brew shellenv)\"" >>~/.profile

  if ! grep -Fq "p10k-instant-prompt" ~/.zshrc; then
    brew install romkatv/powerlevel10k/powerlevel10k
    echo "source $(brew --prefix)/opt/powerlevel10k/powerlevel10k.zsh-theme" >>~/.zshrc

    cp ./.p10k.zsh ~/.p10k.zsh

    sed -i '1iif [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then\n  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"\nfi' ~/.zshrc
    echo "[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh" >> ~/.zshrc
  fi  
   source ~/.zshrc
   $(which zsh)
fi
